// Patch src/data/sourceRegistry.json with the results of the verification passes.
//
// Inputs (all generated by other scripts, never hand-edited):
//   scripts/source_verification.tsv  — first pass  (id, http_code, http_code, content_type)
//   scripts/source_recheck.tsv       — second pass (id, http_code, trailing-slash variant code)
//   sources/robots/index.tsv + *.txt — robots.txt per origin
//
// Writes: src/data/sourceRegistry.json (in place) and docs/SOURCE_MANUAL_QUEUE.json.
// Records observed facts only: no source is marked fetched/parsed/indexed here.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const CHECKED_AT = "2026-07-21";
const REG = "src/data/sourceRegistry.json";

const tsv = (p) =>
  existsSync(p)
    ? readFileSync(p, "utf8").trim().split("\n").filter(Boolean).map((l) => l.split("\t"))
    : [];

const firstPass = new Map(tsv("scripts/source_verification.tsv").map((r) => [r[0], r[1]]));
const recheck = new Map(tsv("scripts/source_recheck.tsv").map((r) => [r[0], r]));

// ---- robots.txt ------------------------------------------------------------
const robots = new Map(tsv("sources/robots/index.tsv").map((r) => [r[0], { code: r[1], file: r[2] }]));

function robotsFile(file) {
  const p = `sources/robots/${file}`;
  return existsSync(p) ? readFileSync(p, "utf8") : null;
}

// Minimal robots parser: rules from the `User-agent: *` groups, longest match wins.
function starRules(txt) {
  const rules = [];
  let inStar = false;
  for (const raw of txt.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, "").trim();
    if (!line) continue;
    const m = line.match(/^([A-Za-z-]+)\s*:\s*(.*)$/);
    if (!m) continue;
    const field = m[1].toLowerCase();
    const value = m[2].trim();
    if (field === "user-agent") inStar = value === "*";
    else if (inStar && (field === "allow" || field === "disallow")) {
      rules.push({ allow: field === "allow", path: value });
    }
  }
  return rules;
}

function robotsVerdict(url) {
  const u = new URL(url);
  const r = robots.get(u.origin);
  if (!r) return { allowed: null, note: "robots.txt not fetched" };
  // A 404/410 means the site publishes no robots.txt, which the standard treats
  // as "no restrictions". Any other non-200 leaves the policy unknown.
  if (r.code === "404" || r.code === "410")
    return { allowed: true, note: "no robots.txt published (HTTP 404)" };
  if (r.code !== "200") return { allowed: null, note: `robots.txt HTTP ${r.code}` };
  const txt = robotsFile(r.file);
  if (txt == null) return { allowed: null, note: "robots.txt missing locally" };
  // An HTML error page served with 200 is not a robots.txt.
  if (/^\s*</.test(txt)) return { allowed: null, note: "robots.txt returned HTML" };
  const rules = starRules(txt);
  if (!rules.length) return { allowed: true, note: "robots.txt has no rules for *" };
  const target = u.pathname + u.search;
  let best = null;
  for (const r of rules) {
    if (r.path === "") continue; // empty Disallow means allow-all
    if (target.startsWith(r.path) && (!best || r.path.length > best.path.length)) best = r;
  }
  if (!best) return { allowed: true, note: "path not disallowed by robots.txt" };
  return {
    allowed: best.allow,
    note: `${best.allow ? "Allow" : "Disallow"}: ${best.path} (robots.txt)`,
  };
}

// ---- accessibility ---------------------------------------------------------
function classify(code) {
  if (code === "200") return "reachable";
  if (code === "403") return "blocked";
  if (code === "000") return "unreachable";
  if (/^5/.test(code)) return "server_error";
  if (/^4/.test(code)) return "not_found";
  return "unverified";
}

const reg = JSON.parse(readFileSync(REG, "utf8"));
const manualQueue = [];

for (const s of reg.sources) {
  const first = firstPass.get(s.source_id);
  if (!first) continue;

  let code = first;
  const notes = [];
  const rc = recheck.get(s.source_id);
  if (rc) {
    const [, second, variant] = rc;
    // Prefer the second pass: it used a 60s timeout, so it distinguishes a slow
    // host from a dead one.
    if (second && second !== "000") {
      code = second;
      if (second !== first) notes.push(`first pass ${first}, 60s re-check ${second}`);
    } else if (variant && variant !== "000" && variant !== "-") {
      code = variant;
      notes.push(`only the trailing-slash variant responded (${variant})`);
    } else {
      notes.push("unreachable on both a 25s and a 60s re-check");
    }
  }

  s.http_status = code === "000" ? null : Number(code);
  s.accessibility = classify(code);
  s.last_checked_at = CHECKED_AT;

  const rv = robotsVerdict(s.index_url);
  s.automation_allowed = rv.allowed;
  notes.push(rv.note);

  const automatable = s.accessibility === "reachable" && rv.allowed === true;
  s.acquisition_mode = automatable ? "automated" : "manual";
  if (!automatable) {
    manualQueue.push({
      source_id: s.source_id,
      authority: s.authority,
      index_url: s.index_url,
      priority: s.priority,
      accessibility: s.accessibility,
      http_status: s.http_status,
      automation_allowed: rv.allowed,
      reason:
        s.accessibility !== "reachable"
          ? `HTTP ${code} — ${s.accessibility}`
          : rv.allowed === false
            ? "disallowed by robots.txt"
            : "robots.txt could not be read; automation not established",
      next_step:
        s.accessibility === "blocked"
          ? "Manual retrieval in a browser; do not attempt to bypass the block."
          : s.accessibility === "unreachable"
            ? "Re-check later; the host did not respond. Possible JS-only or DNS-restricted portal."
            : s.accessibility === "server_error"
              ? "Host is up but erroring; re-check later or use a mirror/alternate index."
              : "Retrieve manually and record provenance by hand.",
    });
  }
  s.notes = notes.join("; ");
}

reg.verification = {
  last_checked_at: CHECKED_AT,
  method:
    "HTTP HEAD-equivalent GET via curl (25s, then 60s re-check for failures); robots.txt read per origin. No page content was scraped in this pass.",
  totals: reg.sources.reduce((a, s) => ((a[s.accessibility] = (a[s.accessibility] || 0) + 1), a), {}),
  manual_queue: manualQueue.length,
};

writeFileSync(REG, JSON.stringify(reg, null, 1) + "\n");
writeFileSync(
  "docs/SOURCE_MANUAL_QUEUE.json",
  JSON.stringify({ generated: CHECKED_AT, count: manualQueue.length, sources: manualQueue }, null, 1) + "\n",
);

console.log("accessibility:", reg.verification.totals);
console.log("manual queue:", manualQueue.length);
console.log(
  "automation_allowed:",
  reg.sources.reduce((a, s) => ((a[String(s.automation_allowed)] = (a[String(s.automation_allowed)] || 0) + 1), a), {}),
);
