// Seed the source registry from the reviewer's link pack (2026-07-19).
// Status starts "unverified" — the verifier fills accessibility results.
import { writeFileSync } from "node:fs";
const S = (id, family, authority, url, use, tier, priority=null) =>
  ({ source_id:id, source_family:family, authority, index_url:url, primary_use:use, tier, priority,
     acquisition_mode:null, automation_allowed:null, last_checked_at:null, http_status:null,
     accessibility:"unverified", fetched:false, parsed:false, indexed:false, linked:false,
     manually_verified:false, notes:"" });
const R = [
 // Tier 1 — TN portals
 S("tn-portal","portal","Government of Tamil Nadu","https://www.tn.gov.in/","Department directory & document discovery",1),
 S("tn-go-dept","go","Government of Tamil Nadu","https://www.tn.gov.in/godept_list.php","GOs by department",1),
 S("tn-dept-docs","policy_note","Government of Tamil Nadu","https://www.tn.gov.in/document_dept_list.php?cate_name=YWxs","Policy Notes, performance budgets",1,2),
 S("tn-announcements","assembly","Government of Tamil Nadu","https://www.tn.gov.in/anndept_list.php","Assembly/department announcements",1),
 S("tn-acts","legislation","Government of Tamil Nadu","https://www.tn.gov.in/act_ordinances.php","State Acts and Ordinances",1),
 S("tn-press","press","Government of Tamil Nadu","https://www.tn.gov.in/press_release.php","Press releases 2021–2026",1,6),
 // Finance
 S("fin-home","budget","TN Finance Department","https://financedept.tn.gov.in/","Finance gateway",1,1),
 S("fin-budget-pubs","budget","TN Finance Department","https://financedept.tn.gov.in/en/budget-publications/","Budget speeches, AFS, demands, estimates",1,1),
 S("fin-policy-notes","policy_note","TN Finance Department","https://financedept.tn.gov.in/en/policy-notes/","Department-wise policy notes",1,2),
 S("fin-highlights","budget","TN Finance Department","https://financedept.tn.gov.in/en/budget-highlights/","Budget highlights",1,1),
 S("ccfms-statutory","other","TN Finance (CCFMS)","https://www.ccfms.tn.gov.in/Welcome/statutory","Statutory bodies directory",1),
 // Assembly
 S("tnla-neva","assembly","TN Legislative Assembly (NeVA)","https://tnla.neva.gov.in/","Proceedings, questions, committees",1,4),
 S("tnla-legacy","assembly","TN Legislative Assembly","https://www.assembly.tn.gov.in/","Legacy Assembly archive",1,4),
 S("tnla-debates","assembly","TN Legislative Assembly","https://www.assembly.tn.gov.in/debates/debates_menu.php","Budget/Demands debates",1,4),
 S("prs-tnla","other","PRS Legislative Research","https://prsindia.org/legislatures/states/16th-tamil-nadu-legislative-assembly-2021-present","Secondary discovery only",1,4),
 // Gazette
 S("gz-home","gazette","Dept. of Stationery & Printing","https://www.stationeryprinting.tn.gov.in/","Gazette authority home",1),
 S("gz-current","gazette","Dept. of Stationery & Printing","https://www.stationeryprinting.tn.gov.in/gazette.php","Current ordinary issues",1),
 S("gz-archives","gazette","Dept. of Stationery & Printing","https://www.stationeryprinting.tn.gov.in/archives.php","Archived issues",1),
 S("gz-extra","gazette","Dept. of Stationery & Printing","https://www.stationeryprinting.tn.gov.in/extra_ordinary_lists.php","Extraordinary notifications",1),
 // eProcurement
 S("tnt-home","tender","TN eProcurement","https://tntenders.gov.in/","Tender system",1,7),
 S("tnt-archive","tender","TN eProcurement","https://tntenders.gov.in/nicgep/app?page=FrontEndTendersInArchive&service=page","Historical tenders",1,7),
 S("tnt-status","tender","TN eProcurement","https://tntenders.gov.in/nicgep/app?page=WebTenderStatusLists&service=page","Tender status/results",1,7),
 S("tnt-org","tender","TN eProcurement","https://tntenders.gov.in/nicgep/app?page=FrontEndTendersByOrganisation&service=page","Org-wise tenders",1,7),
 // CAG
 S("cag-ag1","audit","CAG (AG1 Tamil Nadu)","https://cag.gov.in/ag1/tamil-nadu/en/audit-report","State Finances/performance/compliance audits",1,3),
 S("cag-ag2","audit","CAG (AG2 Tamil Nadu)","https://cag.gov.in/ag2/tamil-nadu/en/audit-report","Additional TN audit reports",1,3),
 S("cag-ae","audit","Pr. AG (A&E) Tamil Nadu","https://cag.gov.in/ae/tamil-nadu/en/state-accounts-report?defuat_account_report_type=360","Finance & Appropriation Accounts",1,3),
 S("cag-pac","audit","CAG / PAC-COPU","https://cag.gov.in/ag1/tamil-nadu/en/page-gssa-tamil-nadu-pac-copu-reports","PAC/COPU follow-up",1,3),
 // Manifesto
 S("dmk-manifesto","manifesto","DMK (party source)","https://www.dmk.in/en/resources/manifesto/","Canonical manifesto discovery",1,5),
 S("dmk-home","manifesto","DMK (party source)","https://www.dmk.in/","Party archive",1,5),
 S("eci-manifesto","other","Election Commission of India","https://eci.gov.in/election-manifestos/","Regulatory context",1,5),
 // Tier 2 — planning/statistics
 S("spc-home","outcome","TN State Planning Commission","https://spc.tn.gov.in/","Reports and studies",2,8),
 S("spc-policies","outcome","TN State Planning Commission","https://spc.tn.gov.in/policies-and-plans-v3/","Plans and policies",2,8),
 S("spc-hdr","outcome","TN State Planning Commission","https://spc.tn.gov.in/hdr-reports-v2/","Human Development Reports",2,8),
 S("spc-sdg","outcome","TN State Planning Commission","https://spc.tn.gov.in/sustainable-development-goals/","SDG reports",2,8),
 S("spc-es2526","outcome","TN State Planning Commission","https://spc.tn.gov.in/wp-content/uploads/Economic-Survey-Highlights-Eng.pdf","Economic Survey 2025–26 highlights (PDF)",2,8),
 S("spc-es2425","outcome","TN State Planning Commission","https://spc.tn.gov.in/wp-content/uploads/ES_TN-English.pdf","Economic Survey 2024–25 highlights (PDF)",2,8),
 S("spc-sif","outcome","TN State Planning Commission","https://spc.tn.gov.in/wp-content/uploads/TN-SIF-2.0.pdf","State Indicator Framework 2.0 (PDF)",2,8),
 S("des-pubs","statistics","TN Dept. of Economics & Statistics","https://www.des.tn.gov.in/en/node/1","Publications gateway",2,9),
 S("des-index","statistics","TN DES","https://des.tn.gov.in/en/node/346","Statistical reports",2,9),
 S("des-handbook","statistics","TN DES","https://des.tn.gov.in/en/node/32","Statistical Handbook",2,9),
 S("des-glance","statistics","TN DES","https://www.des.tn.gov.in/en/node/387","TN at a Glance",2,9),
 S("des-crops","statistics","TN DES","https://des.tn.gov.in/en/node/18","Season & Crop Reports",2,9),
 S("des-income","statistics","TN DES","https://des.tn.gov.in/en/node/20","State Income Estimates",2,9),
 S("tn-opendata","statistics","TN Open Government Data","https://tn.data.gov.in/","Machine-readable datasets",2,9),
 S("tn-sdg","outcome","TN SDG portal","https://tnsdg.tn.gov.in/","State SDG dashboard",2,10),
 S("tn-sdg-district","outcome","TN SDG portal","https://tnsdg.tn.gov.in/reports/indicators/district-level/","District SDG",2,10),
 S("tn-sdg-state","outcome","TN SDG portal","https://tnsdg.tn.gov.in/sustainable-development-goals/state-level-indicators/","State indicators",2,10),
 // Tier 2 — Union cross-checks
 S("rbi-states","independent","Reserve Bank of India","https://www.rbi.org.in/scripts/AnnualPublications.aspx?head=Handbook+of+Statistics+on+Indian+States","State statistics",2,10),
 S("mospi","independent","MoSPI","https://mospi.gov.in/web/mospi/reports-and-publication","PLFS/reports",2,10),
 S("udise","independent","UDISE+ (MoE)","https://dashboard.udiseplus.gov.in/","School education",2,10),
 S("udise-archive","independent","UDISE+ (MoE)","https://dashboard.udiseplus.gov.in/udiseplus-archive","School education archive",2,10),
 S("aishe","independent","AISHE (MoE)","https://aishe.gov.in/","Higher education",2,10),
 S("aishe-reports","independent","AISHE","https://aishe.gov.in/aishe-final-report/","AISHE reports",2,10),
 S("aishe-dash","independent","AISHE","https://dashboard.aishe.gov.in/","AISHE dashboard",2,10),
 S("hmis","independent","Union Health Ministry","https://hmis.mohfw.gov.in/","Health MIS",2,10),
 S("jjm","independent","Jal Jeevan Mission","https://jaljeevanmission.gov.in/","Rural tap water",2,10),
 S("jjm-report","independent","JJM reporting","https://ejalshakti.gov.in/JJM/Login.aspx","JJM reports (login)",2,10),
 S("pmay-u","independent","PMAY-Urban","https://pmay-urban.gov.in/","Urban housing",2,10),
 S("pmay-mis","independent","PMAY MIS","https://pmaymis.gov.in/","Housing MIS",2,10),
 S("niti-sdg","independent","NITI Aayog","https://www.niti.gov.in/divisions/division/sustainable-development-goal","SDG index",2,10),
 S("startup-rank","independent","DPIIT","https://www.startupindia.gov.in/srf/index.html","Startup ranking",2,10),
 S("paimana-dash","independent","MoSPI PAIMANA","https://www.ipm.mospi.gov.in/Home/PublicDashboard","Infra monitoring",2,10),
 S("paimana","independent","MoSPI PAIMANA","https://www.ipm.mospi.gov.in/","Infra monitoring home",2,10),
 // Tier 3 — local bodies / PSUs
 S("gcc","local_body","Greater Chennai Corporation","https://www.chennaicorporation.gov.in/","Local body gateway",3,11),
 S("gcc-council","local_body","GCC","https://chennaicorporation.gov.in/gcc/council/council-resolution/","Council resolutions",3,11),
 S("gcc-tenders","tender","GCC","https://chennaicorporation.gov.in/gcc/tender/","Tender bulletins",3,11),
 S("tidco-reports","psu","TIDCO","https://tidco.com/reports.php","Annual reports",3,12),
 S("tidco-policy","psu","TIDCO","https://www.tidco.com/actandpolicy.php","Acts & policies",3,12),
 S("tidco-tenders","tender","TIDCO","https://www.tidco.com/tender.php","Tenders",3,12),
 S("sipcot-annual","psu","SIPCOT","https://sipcotweb.tn.gov.in/Annul_reports","Annual reports",3,12),
 S("sipcot-reports","psu","SIPCOT","https://sipcotweb.tn.gov.in/Reports_policy","Reports & policies",3,12),
 S("tidel","psu","TIDEL Park","https://tidelpark.com/en/home","IT park",3,12),
 S("tidel-about","psu","TIDEL Park","https://tidelpark.com/en/about-us","Annual reports nav",3,12),
 S("elcot","psu","ELCOT","https://elcot.co.in/annual-reports.html","Annual reports",3,12),
 S("twad","psu","TWAD Board","https://www.twadboard.tn.gov.in/","Water/drainage projects",3,12),
 S("twad-policy","policy_note","TWAD Board","https://www.twadboard.tn.gov.in/policy-notes-documents","Policy notes",3,12),
 S("cmwssb","psu","CMWSSB","https://cmwssb.tn.gov.in/","Chennai water/sewerage",3,12),
 S("cmwssb-balance","psu","CMWSSB","https://cmwssb.tn.gov.in/balance-sheet","Audited reports",3,12),
 S("cmwssb-tenders","tender","CMWSSB","https://cmwssb.tn.gov.in/tenders","Tenders",3,12),
 S("tnhb","psu","TN Housing Board","https://tnhb.tn.gov.in/","Housing board",3,12),
 S("tnhb-policy","policy_note","TN Housing Board","https://tnhb.tn.gov.in/policy-note","Policy notes",3,12),
 S("tnuhdb","psu","TNUHDB","https://tnuhdb.org.in/","Urban habitat portal",3,12),
 S("adb-tnhousing","independent","Asian Development Bank","https://www.adb.org/projects/53067-004/main","Independent project docs",3,12),
 S("tnmsc","psu","TN Medical Services Corp","https://www.tnmsc.tn.gov.in/","Health procurement",3,12),
 S("tnmsc-tenders","tender","TNMSC","https://tnmsc.tn.gov.in/html/tenders.php?action=4&page=1","Tender archive",3,12),
 S("tnmsc-policy","psu","TNMSC","https://tnmsc.tn.gov.in/html/Procurement%20%26%20Tender.php","Procurement policy",3,12),
 S("tnrdc","psu","TN Road Development Co","https://tnrdc.com/","Road projects",3,12),
 S("tnrdc-rti","rti","TNRDC","https://tnrdc.com/right-information-act/","RTI disclosures",3,12),
 S("tnstc","psu","TNSTC/SETC","https://www.tnstc.in/","Transport undertakings",3,12),
 S("tnpdcl","psu","TN Power Distribution Corp","https://www.tnpdcl.org/en/tnpdcl/","Power distribution",3,12),
 S("tnerc","regulator","TNERC","https://www.tnerc.tn.gov.in/","Tariff/case orders",3,13),
 S("tnpcb-policy","policy_note","TN Pollution Control Board","https://tnpcb.gov.in/PolicyNote.php","Env policy notes",3,12),
 S("tnpcb","regulator","TNPCB","https://tnpcb.gov.in/","Consents/monitoring",3,12),
 // Tier 3 — judicial/electoral/RTI
 S("hc-madras","judicial","Madras High Court","https://hcmadras.tn.gov.in/","Judgments",3,13),
 S("sc-judgments","judicial","Supreme Court of India","https://www.sci.gov.in/judgements-judgement-date/","Judgments",3,13),
 S("ngt","judicial","National Green Tribunal","https://www.greentribunal.gov.in/","Environmental cases",3,13),
 S("ngt-orders","judicial","NGT","https://www.greentribunal.gov.in/judgementOrder/zonalbenchwise","Orders search",3,13),
 S("tn-rera","regulator","TN RERA","https://rera.tn.gov.in/","Orders/projects",3,13),
 S("tnsec","electoral","TN State Election Commission","https://tnsec.tn.gov.in/","Local-body elections",3,13),
 S("eci-results","electoral","Election Commission of India","https://results.eci.gov.in/","Election results",3,13),
 S("indiacode","legislation","India Code","https://indiacode.nic.in/","Acts/rules",3,13),
 S("egazette","gazette","Gazette of India","https://egazette.gov.in/","Union Gazette",3,13),
 S("ls-questions","assembly","Lok Sabha","https://sansad.in/ls/questions/questions-and-answers","Union Q&A",3,13),
 S("rs-questions","assembly","Rajya Sabha","https://sansad.in/rs/questions/questions-and-answers","Union Q&A",3,13),
 S("rti-tn","rti","TN RTI Online","https://rtionline.tn.gov.in/","RTI filing",3,14),
 S("tnsic","rti","TN State Information Commission","https://tnsic.gov.in/judgements_public.php","RTI decisions",3,14),
 S("tn-rti-info","rti","Government of Tamil Nadu","https://www.tn.gov.in/rti/sic.htm","PIO/appellate info",3,14),
 S("rti-central","rti","Central RTI Online","https://rtionline.gov.in/","Union RTI filing",3,14),
];
writeFileSync("src/data/sourceRegistry.json", JSON.stringify({generated:"2026-07-21",linkPackDate:"2026-07-19",sources:R},null,1));
console.log("registry sources:", R.length);
